/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../common";
import type { Reverse1, Reverse1Interface } from "../Reverse1";

const _abi = [
  {
    inputs: [],
    name: "LowBalance",
    type: "error",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610100806100206000396000f3fe60806040523660c25760327f30e44d67350413fc4904189352889ef83dfca051f08a1c553861c3cd4550998c60001b60c7565b600047141560965760647ffa893c328b518dd6c62508b8ba53ca8ae7d95b91ee70c7e0889b7444fb9a2d7c60001b60c7565b6040517ffe382aa700000000000000000000000000000000000000000000000000000000815260040160405180910390fd5b60c07f9329b1974a051770b50ee6852e043642e0b05004939ff10cc28dbc6a3918839a60001b60c7565b005b600080fd5b5056fea264697066735822122047bdc6484dadae57cb6f2b61c195e7af0a53dfe92776cc0579c06915906551a264736f6c63430008080033";

type Reverse1ConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: Reverse1ConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Reverse1__factory extends ContractFactory {
  constructor(...args: Reverse1ConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<Reverse1> {
    return super.deploy(overrides || {}) as Promise<Reverse1>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): Reverse1 {
    return super.attach(address) as Reverse1;
  }
  override connect(signer: Signer): Reverse1__factory {
    return super.connect(signer) as Reverse1__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): Reverse1Interface {
    return new utils.Interface(_abi) as Reverse1Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Reverse1 {
    return new Contract(address, _abi, signerOrProvider) as Reverse1;
  }
}
