/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { SimpleStorage__factory } from "./SimpleStorage__factory";
export { Test__factory } from "./Test__factory";
