/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface Reverse2Interface extends utils.Interface {
  functions: {
    "addFund()": FunctionFragment;
    "begin()": FunctionFragment;
    "showBalance()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "addFund" | "begin" | "showBalance"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "addFund", values?: undefined): string;
  encodeFunctionData(functionFragment: "begin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "showBalance",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "addFund", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "begin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "showBalance",
    data: BytesLike
  ): Result;

  events: {};
}

export interface Reverse2 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: Reverse2Interface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addFund(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    begin(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    showBalance(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  addFund(
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  begin(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  showBalance(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    addFund(overrides?: CallOverrides): Promise<void>;

    begin(overrides?: CallOverrides): Promise<void>;

    showBalance(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    addFund(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    begin(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    showBalance(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    addFund(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    begin(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    showBalance(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
