/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export interface TestInterface extends utils.Interface {
  functions: {
    "set(uint256)": FunctionFragment;
    "storedData()": FunctionFragment;
    "storedData2()": FunctionFragment;
    "storedData4()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "set" | "storedData" | "storedData2" | "storedData4"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "set",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "storedData",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "storedData2",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "storedData4",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "set", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "storedData", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "storedData2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "storedData4",
    data: BytesLike
  ): Result;

  events: {};
}

export interface Test extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TestInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    set(
      x: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    storedData(overrides?: CallOverrides): Promise<[BigNumber]>;

    storedData2(overrides?: CallOverrides): Promise<[BigNumber]>;

    storedData4(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  set(
    x: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  storedData(overrides?: CallOverrides): Promise<BigNumber>;

  storedData2(overrides?: CallOverrides): Promise<BigNumber>;

  storedData4(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    set(
      x: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    storedData(overrides?: CallOverrides): Promise<BigNumber>;

    storedData2(overrides?: CallOverrides): Promise<BigNumber>;

    storedData4(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    set(
      x: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    storedData(overrides?: CallOverrides): Promise<BigNumber>;

    storedData2(overrides?: CallOverrides): Promise<BigNumber>;

    storedData4(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    set(
      x: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    storedData(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    storedData2(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    storedData4(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
