/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as testSol from "./test.sol";
export type { testSol };
export type { SimpleStorage } from "./SimpleStorage";
export * as factories from "./factories";
export { SimpleStorage__factory } from "./factories/SimpleStorage__factory";
export type { Test } from "./test.sol/Test";
export { Test__factory } from "./factories/test.sol/Test__factory";
